[package]
name = "freighter-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
metrics = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
