[workspace]
resolver = "2"
members = [
    "freighter",
    "freighter-auth",
    "freighter-index",
    "freighter-server",
    "freighter-storage",
]

[workspace.dependencies]
freighter = { path = "freighter" }
freighter-auth = { path = "freighter-auth", registry = "nkcompute", version = "0.0.2" }
freighter-index = { path = "freighter-index", registry = "nkcompute", version = "0.0.2" }
freighter-server = { path = "freighter-server", registry = "nkcompute", version = "0.0.2" }
freighter-storage = { path = "freighter-storage", registry = "nkcompute", version = "0.0.2" }

anyhow = "1.0.71"
async-trait = "0.1.68"
axum = { version = "0.6.18", default-features = false }
axum-extra = "0.7.4"
aws-region = "0.25.3"
bytes = "1.4.0"
clap = "4.2.7"
deadpool-postgres = "0.10.5"
metrics = "0.21.0"
metrics-exporter-prometheus = { version = "0.12.1", default-features = false }
postgres-types = "0.2.5"
rand = "0.8.5"
rust-s3 = "0.33.0"
semver = "1.0.17"
serde = "1.0.162"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
sha2 = "0.10.6"
thiserror = "1.0.40"
tokio = "1.28.1"
tokio-stream = { version = "0.1.14", default-features = false }
tower-http = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[profile.release]
debug = true
