[workspace]
resolver = "2"
members = [
    "ever-given",
    "freeport-api",
    "freeport-server"
]

[workspace.dependencies]
ever-given = { path = "ever-given", registry = "nkcompute" }
freeport-api = { path = "freeport-api", version = "0.0.4", registry = "nkcompute" }

axum = { version = "0.6.18", default-features = false }
axum-extra = "0.7.4"
aws-creds = "0.35.0"
aws-region = "0.25.3"
clap = "4.2.7"
deadpool-postgres = "0.10.5"
metrics = "0.21.0"
metrics-exporter-prometheus = { version = "0.12.1", default-features = false }
md5 = "0.7.0"
postgres-types = "0.2.5"
rand = "0.8.5"
reqwest = "0.11.17"
rust-s3 = "0.33.0"
semver = "1.0.17"
serde = "1.0.162"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
sha2 = "0.10.6"
tokio = "1.28.1"
tokio-stream = { version = "0.1.14", default-features = false }
tower-http = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[profile.release]
debug = true
