[workspace]
members = [
    "freeport-server"
]

[workspace.dependencies]
axum = { version = "0.6.18" }
semver = { version = "1.0.17" }
tokio = { version = "1.28.1" }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }