[package]
name = "freighter-storage"
version = "0.0.3"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Noah Kennedy <nomaxx117@gmail.com>"]
publish = ["nkcompute"]

[features]
s3-backend = ["aws-region", "rust-s3"]

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
async-trait = { workspace = true }
aws-region = { workspace = true, features = ["serde"], optional = true }
bytes = { workspace = true }
metrics = { workspace = true }
rust-s3 = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }
